### ISSUE TITLE
PHP Notice: Undefined variable: asuevent_image_url when adding new ASU Event node

### ISSUE THREAD

**Issue by ryanjbonnell** [ASU/webspark-drops-drupal7#150]
When adding or viewing a new ASU Event without an image, the following PHP notice is shown:

> Notice: Undefined variable: asuevent_image_url in include() (line 35 of /profiles/openasu/modules/webspark_featurescustom/webspark_newsevents/templates/views-view-fields--asu-newsevent-images--panel-pane-1.tpl.php).

This message is shown on the ASU Event node detail page when a file has not been added to the Image field (`field_asuevent_image`).

The behavior is present in the latest release, Webspark v1.13.15 (Bellingham) as of April 2015.

**Comment by bjdevil21** [comment]
Hi, Ryan - Thanks for letting us know. We're looking into it now.

**Comment by bjdevil21** [comment]
We're having trouble recreating this issue. You're manually creating an ASU Event node (i.e. /node/add/asu_event), on beta3 of the webspark_newsevents (step 2) module, right? And you ran the DB updates, etc.? If so, can you give an exact set of steps to recreate?

**Comment by ryanjbonnell** [comment]
I originally noticed the problem on an upgraded Webspark installation, but I can confirm this behavior exists even on a brand-new, "clean" installation.

This was tested from a new site spun-up at Pantheon installed on an empty (wiped) environment.

Package | Version
--- | ---
Webspark | 1.13.15 (Bellingham) 
Webspark News and Events Prerequisite (Step 1) | 7.x-1.0-beta1
Webspark News and Events (Step 2) | 7.x-1.0-beta3

To recreate the problem:

1. Spin up a new site at Pantheon
2. Enable Webspark News and Events Prerequisite (Step 1)
3. Enable Webspark News and Events (Step 2)
4. Go to `/node/add/asu_event`
5. Fill in the Node title
6. Publish the node

The PHP notice will appear on the ASU Event node detail page (see screenshot below):

![screenshot](https://cloud.githubusercontent.com/assets/133372/14900651/81a1fc36-0d46-11e6-959d-41edc347d7f2.png)

The message is output due to the variable `$asuevent_image_url` not being correctly initialized in the [Views template file][1] because the conditional check `isset($fields['field_asuevent_image'])` is returning a false positive.

[1]: https://github.com/ASU/webspark-drops-drupal7/blob/master/profiles/openasu/modules/webspark_featurescustom/webspark_newsevents/templates/views-view-fields--asu-newsevent-images--panel-pane-1.tpl.php

**Comment by bjdevil21** [comment]
Found the issue and patched. Being tested by QA. Closing here. Thanks again for the report!
