### ISSUE TITLE
[ASU Spotlight] Fields are required by default

### ISSUE THREAD

**Issue by stevesmename** [ASU/webspark-drops-drupal7#187]
Hey @ctestama - question for you, is it safe to do a hook_form_alter on a site I'm working on so that many of the spotlight fields can be optional? I haven't tested but I thought they could been made required because of styling issues that would possibly occur. 

Let me know if you can recall any issues. thanks!

**Comment by bjdevil21** [comment]
Hi, Steve - What are the machine names and labels of the fields you are talking about?

**Comment by stevesmename** [comment]
Apologize for delay; When the admin adds the Spotlight pane into the page then initially all the fields are required. The admin enters in data into each and every field (fake, lorem ipsum, etc) - saves - then admin edits the Spotlight pane they just added and all the fields are now optional (removes all fake lorem ipsum). The Spotlight pane should be cleaned up so proper (and consistent) validation is done when adding and editing the pane.

I'd suggest only Image upload be the required field, all others can be optional.
