### ISSUE TITLE
ASU Directory causing unrelated error in Views Bulk Operations

### ISSUE THREAD

**Issue by travisbutterfield** [ASU/webspark-drops-drupal7#189]
I am trying to perform a Views Bulk Operation "change value" function on a content type that is completely unrelated to the ASU Directory, but I keep getting the following error message which prevents me from proceeding: "ASU Directory root department is not valid." I'm not actively using the ASU Directory Integration Reinvented module (version 7.x-1.5), although it is enabled.

I have found a workaround which allows me to proceed with the VBO, but it is a hassle to have to do it every time. I find that I have to click the on/off switch in the VBO interface for ASU Directory, which then reveals several options. If I go into the Content tab and Browse to find my department and select it, then disable the ASU Directory switch (because I don't want to make a VBO change related to that module), it allows me to proceed.  ![workaround1](https://cloud.githubusercontent.com/assets/19654875/22520716/b0c98bf2-e872-11e6-9cd5-a82fcaea870f.png)

**update** 
I just found that if I use the "Type" filter in addition to the "Taxonomy" filter I was using in my VBO interface, it doesn't give me the error AND it doesn't force me to fill out the ASU Directory thing to select my department. So, this second workaround makes this bug less urgent. But, it's probably something that should be addressed at some point.

Thanks! :-)

**Comment by ctestama** [comment]
Thanks for the heads up!  I've created a webspark JIRA ticket to track the issue.
