### ISSUE TITLE
how to update contrib modules

### ISSUE THREAD

**Issue by alee** [ASU/webspark-drops-drupal7#240]
I'm setting up a WYSIWYG editor for our content editors at complexity.asu.edu and discovered that the wysiwyg module (located at `profiles/openasu/modules/contrib/wysiwyg`)  is ancient and as a result cannot detect modern versions of the various wysiwig editor providers like ckeditor or tinymce, (see [supported editor matrix](https://www.drupal.org/docs/7/modules/wysiwyg/supported-editors-matrix)). 

What's the approved way for updating contrib modules in a Pantheon Webspark install - should I manually download the latest version and place it in the `profiles/openasu/modules/contrib/wysiwyg` directory? I'd like to keep pulling in upstream updates and minimize merge conflicts.

Thanks!

**Comment by dherbold** [comment]
+1
