### ISSUE TITLE
Duplicate HTML attribute ID "footer" when using Panopoly Moscone layout

### ISSUE THREAD

**Issue by ryanjbonnell** [ASU/webspark-drops-drupal7#57]
When using Webspark and the bundled theme, Innovation, there is a bug where more than one HTML element with the ID of 'footer' gets output.

This issue occurs "out of the box" using all default settings and is easily reproducible.

Consider the following code excerpt from Innovation's [`page.tpl.php`][1], shown below:

```html
  <!-- Page Footer -->
  <footer id="footer">
    <div class="container">
      <div class="row row-full">
      	<?php print render($page['footer']); ?>
      </div>
    </div>
  </footer><!-- /#footer -->
```

Steps to reproduce bug:

1. Spin-up or use an existing Webspark distribution
2. Add a new node, selecting the built-in "Content Page" type

  > By default, the page layout will use the Panopoly template "Moscone"

3. View the HTML page source
4. Search for the phrase `id="footer"`
5. The results will highlight two matches (see screenshot, below)

Notice the duplicate 'footer' attribute IDs &mdash; one resulting from the Panopoly Moscone layout (highlighted in orange) and the other from the ASU Innovation theme (highlighted in yellow).

![](http://i.stack.imgur.com/Y2hfX.png)

This is problematic for several reasons:

* Possible CSS styling and conflicts
* Unique DOM selection using JavaScript
* Maintainability problems with widespread Webspark use
* Frustration in debugging, since IDs are required to be unique
* The Moscone layout from Panopoly is the default layout for all "Content Page" node types

There may be other, similar instances or conflicts, so further examination is needed.

Tested using Panopoly 7.x-1.13 with ASU Webspark 1.13.2 "Oklahoma" and ASU Innovation theme 7.x-1.0-beta6.

[1]: https://github.com/ASU/webspark-drops-drupal7/blob/master/profiles/openasu/themes/innovation/templates/page.tpl.php#L149

[2]: https://webspark.asu.edu/notifications/webspark-1133-oklahoma-release

**Comment by bjdevil21** [comment]
Hi, Ryan. I've reported this and it will be fixed in the next release. The fix will likely be changing the 2nd id="footer" at the bottom to id="page-footer".

Also, if you have access to JIRA at ASU, enter these bugs/issues there as well. That's our primary issue queue for Webspark issues, and you may not get as quick of a response here.

And thanks for reporting this!

**Comment by bjdevil21** [comment]
Added to utah build and will go out in that upcoming/next release.
